title: Cyber Ceej
   description: Thinking out loud for 
   url: "https://Ceej-16.github.io"
   baseurl: ""
   
   # Build settings
   markdown: kramdown
   theme: minima
   
   # Exclude from build
   exclude:
     - .obsidian/
     - README.md