title: Cyber Ceej
   description: A place for me to think out loud about anything cyber
   url: "https://Ceej-16.github.io"
   baseurl: ""
   
   # Build settings
   markdown: kramdown
   theme: minima
   
   # Exclude from build
   exclude:
     - .obsidian/
     - README.md